block: fiops-iosched: Fix implicit declaration of function in fiops_merge
../block/fiops-iosched.c: In function 'fiops_merge':
../block/fiops-iosched.c:561:14: error: implicit declaration of function 'elv_rq_merge_ok'; did you mean 'blk_rq_merge_ok'? [-Werror=implicit-function-declaration]
  if (__rq && elv_rq_merge_ok(__rq, bio)) {
              ^~~~~~~~~~~~~~~
              blk_rq_merge_ok
../block/fiops-iosched.c: At top level:
../block/fiops-iosched.c:747:4: error: 'struct elevator_ops' has no member named 'elevator_allow_merge_fn'; did you mean 'elevator_allow_rq_merge_fn'?
   .elevator_allow_merge_fn = fiops_allow_merge,
    ^~~~~~~~~~~~~~~~~~~~~~~
    elevator_allow_rq_merge_fn

Signed-off-by: Fiqri Ardyansyah <fiqri15072019@gmail.com>
(cherry picked from commit f681e43b7a1e12822721f77bbcd82f879c005a47)
(cherry picked from commit 19f45961603f9015c305cafbd306ae9951dab64a)