drivers/staging: qcacld-3.0: syntax fix
after the fix for GCC 10 on ACPICA problems like these arose
"../drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:1485:2: error: this 'if' clause does not guard ... [ -Werror = misleading-indentation]
 1485 | if (wlan_cfg_get_int (pMac, WNI_CFG_MAX_SP_LENGTH, & val)! = eSIR_SUCCESS) "

with this commit I fixed the syntax and indentation

(cherry picked from commit b62d35fdb2cfa1f82409ac8c31e4cb7265f900b0)
(cherry picked from commit 29a22699a61c144633a7179ebd4b00e5949cef7f)